version: "{branch} {build}"

install:
  - choco install firefox
  - choco install googlechrome

build_script:
  - gradlew.bat test

cache:
  - C:\Users\appveyor\.gradle

environment:
  matrix:
  - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0

matrix:
  fast_finish: true