version: "{branch} {build}"

build:
  verbosity: detailed

install:
  - choco install firefox
  - choco install googlechrome

test_script:
  - gradlew.bat test

branches:
  only:
    - master

cache:
  - C:\Users\appveyor\.gradle
